### ISSUE TITLE
RSVP: 18 MAY 2019

### ISSUE THREAD

**Issue by joshuamabina** [forlooptanzania/ride-my-way#12]
Hi there,

Hope you are just as excited about our next meetup as we are. Hurrah!

To shake things up, and further cultivate the Git, GitHub and GitHub Flow knowledge we have amassed, thus far, we come up with a fun way to **confirm your attendance**, this time.

The steps are simple:

- Fork this repository
- Clone your repository
- Edit the [RSVP-MAY-18-2019](https://github.com/forlooptanzania/ride-my-way/blob/master/RSVP-MAY-18-2019.md) file. Use the template below.

```
## Full Name (Female or Male)

Fun fact: The quick brown fox jumps over the lazy dog.

- Email [fullname@example.com](mailto:fullname@example.com)
- GitHub [fullname](https://github.com/fullname)
- Twitter [@fullname](https://twitter.com/fullname)
```

- Make a commit using the style below:

```
docs: update RSVPs

Added Full Name

See #12 
```

- Push to your own repository e.g. **fullname/ride-my-way**
- Make a pull request against **forlooptanzania/ride-my-way**

Helpful links:

- [Fork a repo](https://help.github.com/en/articles/fork-a-repo)
- [How to write a Git commit message](https://chris.beams.io/posts/git-commit/)
- [About pull requests](https://help.github.com/en/articles/about-pull-requests)
- [Mastering markdown](https://guides.github.com/features/mastering-markdown/)
- [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

**Comment by frank2ny** [comment]
hellow
do we have to create a new branch for this task

**Comment by BaharaJr** [comment]
> hello
> do we have to create a new branch for this task?

All you have to do is fork and clone the repo to edit the RSVPs file, no branch needed. (According to my knowledge)

**Comment by joshuamabina** [comment]
Oops! Please refer to this [one](https://github.com/forlooptanzania/forlooptanzania.github.io/issues/4).
