### ISSUE TITLE
Can not update value of state

### ISSUE THREAD

**Issue by nelsonfrank** [forlooptanzania/ride-my-way#17]
I was trying to call ` this.state.name ` on the function handleChange then try to call the function on Button  OnClick event
```
state = {
     name: "Leo"
}
handleChange(){
      this.state.name;
}
render(){
    return(
        <button onClick={handleChange}> Click Me</button>
    );
}

```

**Comment by karimkawambwa** [comment]
@Nelsonfrank you will have to bind the context to that function.

So:

```
<button onClick={handleChange.bind(this)}> Click Me</button>
```

You can arrow this by using the // ES6 arrow function to capture this context:

```
handleChange = () => {...}
```
